name: Secure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit scan
        run: |
          pip install bandit
          bandit -r . -ll --skip B101

      - name: Build Docker image
        run: docker build -t deepdast .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: deepdast
          format: table
          exit-code: 1
          vuln-type: os,library

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: Anita-ani           # e.g., anita-dev or your GitHub username
          projectKey: Anita-ani_DeepDAST           # e.g., yourusername_deepdast
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
